# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustInService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True)),
                ('nick_name', models.CharField(max_length=16, null=True)),
                ('mobile_no', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('create_time', models.DateTimeField(null=True, verbose_name='create time')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='modified time')),
                ('age', models.IntegerField(null=True)),
                ('teacher_name', models.CharField(max_length=16, null=True)),
                ('sales_id', models.BigIntegerField(null=True)),
                ('birthday', models.DateField(null=True, verbose_name='birthday')),
                ('classtime', models.DateTimeField(null=True, verbose_name='classtime')),
                ('contract_type', models.CharField(max_length=16, null=True)),
                ('contract_time', models.DateTimeField(null=True, verbose_name='contract_time')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, null=True)),
                ('nick_name', models.CharField(max_length=16, null=True)),
                ('mobile_no', models.CharField(max_length=16, null=True)),
                ('address', models.CharField(max_length=128, null=True)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('create_time', models.DateTimeField(null=True, verbose_name='create time')),
                ('modified_time', models.DateTimeField(null=True, verbose_name='modified time')),
                ('age', models.IntegerField(null=True)),
                ('is_expr', models.CharField(max_length=1, null='N')),
                ('is_appoints', models.CharField(max_length=1, null='N')),
                ('expr_time', models.DateTimeField(null=True, verbose_name='expr time')),
                ('teacher_name', models.CharField(max_length=16, null=True)),
                ('sales_id', models.BigIntegerField(null=True)),
                ('appoints_time', models.DateTimeField(null=True, verbose_name='appoints time')),
                ('is_service', models.CharField(max_length=1, null='N')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer_type', models.CharField(max_length=16, null=True)),
                ('refer_id', models.BigIntegerField(null=True)),
                ('remark_time', models.DateTimeField(null=True)),
                ('remark', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=16, null=True)),
                ('sales_mobile', models.CharField(max_length=16, null=True)),
                ('username', models.CharField(max_length=16, null=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('is_super', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=16, null=True)),
                ('teacher_mobile', models.CharField(max_length=16, null=True)),
            ],
        ),
    ]
