# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='modified_time',
            field=models.DateTimeField(default='2012-01-01 00:00:00', verbose_name='modified time'),
            preserve_default=False,
        ),
    ]
