# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custinservice',
            name='classtime',
            field=models.DateField(null=True, verbose_name='classtime'),
        ),
    ]
