# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='refer_id',
            field=models.BigIntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remark',
            name='refer_type',
            field=models.CharField(default='leads', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remark',
            name='remark',
            field=models.CharField(default='test', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_time',
            field=models.DateTimeField(default='2016-04-04 00:00:00'),
            preserve_default=False,
        ),
    ]
