# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160416_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_name', models.CharField(max_length=16)),
                ('sales_mobile', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_mobile',
            field=models.CharField(default='18657100339', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='Jolin', max_length=16),
            preserve_default=False,
        ),
    ]
