# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
         ('crm', '0003_auto_20160417_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='password',
            field=models.CharField(default='helloworld', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='username',
            field=models.CharField(default='test', max_length=16),
            preserve_default=False,
        ),
    ]
