# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20160417_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_super',
            field=models.CharField(default='N', max_length=1),
            preserve_default=False,
        ),
    ]
