# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_sales_is_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appoints_time',
            field=models.DateTimeField(default='2015-05-28 00:00:00', verbose_name='appoints time'),
            preserve_default=False,
        ),
    ]
